language: java

jdk:
  - openjdk8

services:
  - docker

addons:
  sonarcloud:
    organization: "openwms-github"

script:
  - sonar-scanner
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install deploy sonar:sonar

after_success:
  - docker build -t openwms/org.openwms.tms.transportation:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master